version: "3.7"
name: "ven"
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: ${DATABASE_RESTART:-no}
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${DATABASE_PORT:-3306}:${DATABASE_PORT:-3306}
  # prisma-mysql-api:
  #   environment:
  #     - PRODUCTION_PORT=${PRODUCTION_PORT}
  #   stdin_open: true
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: prisma-mysql-api
  #   depends_on:
  #     - db
  #   ports:
  #     -  ${PRODUCTION_PORT:-4000}:${PRODUCTION_PORT:-4000}
  #   restart: always
volumes:
  mysql_data:
