export enum ModuleKey {
	ModuleDepartments = "module_departments",
	ModuleCompanies = "module_companies",
	ModuleUsers = "module_users",
	ModuleTimesheets = "module_timesheets",
	ModuleClients = "module_clients",
	ModuleRoles = "module_roles",
	ModuleProjects = "module_projects",
}

export enum PermissionKey {
	DepartmentsCreate = "permission_departments_create",
	DepartmentsUpdate = "permission_departments_update",
	DepartmentsDelete = "permission_departments_delete",
	DepartmentsView = "permission_departments_view",
	CompaniesCreate = "permission_companies_create",
	CompaniesUpdate = "permission_companies_update",
	CompaniesDelete = "permission_companies_delete",
	CompaniesView = "permission_companies_view",
	UsersCreate = "permission_users_create",
	UsersUpdate = "permission_users_update",
	UsersDelete = "permission_users_delete",
	UsersView = "permission_users_view",
	TimesheetsCreate = "permission_timesheets_create",
	TimesheetsUpdate = "permission_timesheets_update",
	TimesheetsDelete = "permission_timesheets_delete",
	TimesheetsView = "permission_timesheets_view",
	ClientsCreate = "permission_clients_create",
	ClientsUpdate = "permission_clients_update",
	ClientsDelete = "permission_clients_delete",
	ClientsView = "permission_clients_view",
	RolesCreate = "permission_roles_create",
	RolesUpdate = "permission_roles_update",
	RolesDelete = "permission_roles_delete",
	RolesView = "permission_roles_view",
	ProjectsCreate = "permission_projects_create",
	ProjectsUpdate = "permission_projects_update",
	ProjectsDelete = "permission_projects_delete",
	ProjectsView = "permission_projects_view",
}
